Demo.PL/Controllers/EmployeeController.cs
using AutoMapper;
using Demo.BLL.Interfaces;
using Demo.BLL.Repositories;
using Demo.DAL.Models;
using Demo.PL.Helpers;
using Demo.PL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Demo.PL.Controllers;
[Authorize]
public class EmployeeController : Controller
{
    private readonly IMapper _mapper;
    private readonly IUnitOfWork _unitOfWork;

    //private readonly IEmployeeRepository _employeeRepository;
    //private readonly IDepartmentRepository _departmentRepository;

    public EmployeeController(IMapper mapper,
        IUnitOfWork unitOfWork
        
        /*IEmployeeRepository employeeRepository,IDepartmentRepository departmentRepository*/)
    {
        _mapper = mapper;
        _unitOfWork = unitOfWork;
        //_employeeRepository = employeeRepository;
        //_departmentRepository = departmentRepository; //Because we don't need an object for all the actions
    }

    public IActionResult Index(string SearchInput)
    {
        var employees = Enumerable.Empty<Employee>();

        if(string.IsNullOrEmpty(SearchInput))
             employees = _unitOfWork.EmployeeRepository.GetAll();
        
        else
             employees = _unitOfWork.EmployeeRepository.SearchByName(SearchInput.ToLower());

        var mappedEmps = _mapper.Map<IEnumerable<Employee>, IEnumerable<EmployeeViewModel>>(employees);

        return View(mappedEmps);
    }

    [HttpGet]
    public IActionResult Create()
    {
        //ViewBag.Departments = _departmentRepository.GetAll();
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(EmployeeViewModel employeeVM)
    {
        if (ModelState.IsValid)
        {
            employeeVM.ImageName=DocumentSettings.UploadFile(employeeVM.Image, "Images");
            //Manual Mapping
            //var mappedEmp = new Employee()
            //{
            //    Name = employeeVM.Name,
            //    Salary = employeeVM.Salary,
            //    PhoneNumber = employeeVM.PhoneNumber,
            //    Email = employeeVM.Email,
            //    Age = employeeVM.Age,
            //    IsActive = employeeVM.IsActive,
            //    HireDate = employeeVM.HireDate,
            //    Address = employeeVM.Address
            //};
            var mappedEmp=_mapper.Map<EmployeeViewModel,Employee>(employeeVM);   
            
                _unitOfWork.EmployeeRepository.Add(mappedEmp);

            var count = _unitOfWork.Complete();
            if (count > 0)
                TempData["Message"] = "Employee is created successfully";

            else
                TempData["Message"] = "An Error has occured, Employee not created";

            return RedirectToAction(nameof(Index));
        }

        return View(employeeVM);
    }

    public IActionResult Details(int? id, string ViewName = "Details")
    {
        if (!id.HasValue)
            return BadRequest();

        var employee = _unitOfWork.EmployeeRepository.Get(id.Value);

        var mappedEmp = _mapper.Map<Employee, EmployeeViewModel>(employee);

        if (employee is null)
            return NotFound();

        return View(ViewName, mappedEmp);
    }

    public IActionResult Edit(int? id)
    {
        ///if (!id.HasValue)
        ///    return BadRequest();
        ///var department = _departmentRepository.Get(id.Value);
        ///if (department is null)
        ///    return NotFound();
        ///return View(department);
        //ViewBag.Departments = _departmentRepository.GetAll();

        return Details(id, "Edit");
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit([FromRoute] int id, EmployeeViewModel employeeVM)
    {
        if (id != employeeVM.Id)
            return BadRequest();

        if (ModelState.IsValid)
        {
            try
            {
                var oldEmployee = _unitOfWork.EmployeeRepository.Get(id);

                _unitOfWork.EmployeeRepository.Detach(oldEmployee);

                if (!string.IsNullOrEmpty(oldEmployee.ImageName))
                    DocumentSettings.DeleteFile("Images", oldEmployee.ImageName);

                var mappedEmp = _mapper.Map<EmployeeViewModel, Employee>(employeeVM);

                mappedEmp.ImageName = DocumentSettings.UploadFile(employeeVM.Image, "Images");

                _unitOfWork.EmployeeRepository.Update(mappedEmp);

                _unitOfWork.Complete();

                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {

                //1. Log Exception
                //2. Friendly message
                ModelState.AddModelError(string.Empty, ex.Message);
            }
        }


        return View(employeeVM);
    }

    public IActionResult Delete(int? id)
    {

        return Details(id, "Delete");
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Delete([FromRoute] int id, EmployeeViewModel employeeVM)
    {
        if (id != employeeVM.Id)
            return BadRequest();

        try
        {
            var mappedEmp = _mapper.Map<EmployeeViewModel, Employee>(employeeVM);

            _unitOfWork.EmployeeRepository.Delete(mappedEmp);

           var count= _unitOfWork.Complete();

            if (count > 0)
                DocumentSettings.DeleteFile(employeeVM.ImageName, "Images");

            return RedirectToAction(nameof(Index));
        }
        catch (Exception ex)
        {
            //1. Log Exception
            //2. Friendly message

            ModelState.AddModelError(string.Empty, ex.Message);
            return View(employeeVM);
        }
    }
}

Demo.PL/Controllers/RoleController.cs
using AutoMapper;
using Demo.DAL.Models;
using Demo.PL.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace Demo.PL.Controllers
{
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IMapper _mapper;
        private readonly UserManager<ApplicationUser> _userManager;

        public RoleController(RoleManager<IdentityRole>roleManager,IMapper mapper,UserManager<ApplicationUser>userManager)
        {
            _roleManager = roleManager;
            _mapper = mapper;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(string name)
        {
            if (string.IsNullOrEmpty(name))
            {
                var roles = _roleManager.Roles.Select(r => new RoleViewModel()
                {
                    Id = r.Id,
                    RoleName= r.Name
                }).ToList();
                return View(roles);
            }
            else
            {
                var role = await _roleManager.FindByNameAsync(name);

                if (role is not null)
                {
                    var mappedRole = new RoleViewModel()
                    {
                        Id = role.Id,
                        RoleName = role.Name
                    };
                    return View(new List<RoleViewModel>() { mappedRole });
                }

                return View(Enumerable.Empty<RoleViewModel>());
            }

        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(RoleViewModel model)
        {
            if(ModelState.IsValid)
            {
                var mappedRole=_mapper.Map<RoleViewModel,IdentityRole>(model);

                await _roleManager.CreateAsync(mappedRole);

                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        public async Task<IActionResult> Details(string id, string ViewName = "Details")
        {
            if (id is null)
                return BadRequest();

            var role = await _roleManager.FindByIdAsync(id);

            if (role is null)
                return NotFound();

            var mappedRole = _mapper.Map<IdentityRole, RoleViewModel>(role);


            return View(ViewName, mappedRole);
        }

        public async Task<IActionResult> Edit(string id)
        {

            return await Details(id, "Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] string id, RoleViewModel updatedRole)
        {
            if (id != updatedRole.Id)
                return BadRequest();

            //if (ModelState.IsValid)
            //{
            try
            {
                var role = await _roleManager.FindByIdAsync(id);

                role.Name = updatedRole.RoleName;

                await _roleManager.UpdateAsync(role);

                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {

                //1. Log Exception
                //2. Friendly message
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            //}


            return View(updatedRole);
        }

        public async Task<IActionResult> Delete(string id)
        {

            return await Details(id, "Delete");
        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmDelete(string id)
        {

            try
            {
                var role = await _roleManager.FindByIdAsync(id);

                await _roleManager.DeleteAsync(role);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                //1. Log Exception
                //2. Friendly message

                ModelState.AddModelError(string.Empty, ex.Message);
                return RedirectToAction("Error", "Home");
            }
        }

        public async Task<IActionResult> AddOrRemoveUsers(string RoleId)
        {
            var role = await _roleManager.FindByIdAsync(RoleId);

            if (role == null)
                return BadRequest();

            ViewBag.RoleId = RoleId;

            var usersInRole = new List<UserInRoleViewModel>();

            foreach (var user in await _userManager.Users.ToListAsync())
            {
                var userInRole = new UserInRoleViewModel
                {
                    UserName = user.UserName,
                    UserId = user.Id,
                };

                if (await _userManager.IsInRoleAsync(user, role.Name))
                    userInRole.IsSelected = true;
                else userInRole.IsSelected = false;

                usersInRole.Add(userInRole);
            }
            return View(usersInRole);
        }

        [HttpPost]
        public async Task<IActionResult> AddOrRemoveUsers(List<UserInRoleViewModel> users, string RoleId)
        {
            var role = await _roleManager.FindByIdAsync(RoleId);

            if (role == null)
                return NotFound();

            if (ModelState.IsValid)
            {
                foreach (var user in users)
                {
                    var appUser = await _userManager.FindByIdAsync(user.UserId);
                    if (appUser != null)
                    {
                        if (user.IsSelected && !(await _userManager.IsInRoleAsync(appUser, role.Name)))
                            await _userManager.AddToRoleAsync(appUser, role.Name);
                        else if (!user.IsSelected && (await _userManager.IsInRoleAsync(appUser, role.Name)))
                            await _userManager.RemoveFromRoleAsync(appUser, role.Name);
                    }

                }
                return RedirectToAction(nameof(Update), new { id = RoleId });
            }
            return View(users);
        }
    }
}

Demo.PL/Controllers/UserController.cs
using AutoMapper;
using Demo.DAL.Models;
using Demo.PL.Helpers;
using Demo.PL.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Demo.PL.Controllers
{
	public class UserController : Controller
	{
        private readonly IMapper _mapper;
        private readonly UserManager<ApplicationUser> _userManager;
		private readonly SignInManager<ApplicationUser> _signInManager;

		public UserController(IMapper mapper,UserManager<ApplicationUser>userManager,SignInManager<ApplicationUser>signInManager)
        {
            _mapper = mapper;
            _userManager = userManager;
			_signInManager = signInManager;
		}

		public async Task<IActionResult> Index(string email)
		{
			if(string.IsNullOrEmpty(email))
			{
				var users = _userManager.Users.Select(u => new UserViewModel()
				{
					Id = u.Id,
					FName = u.FName,
					LName = u.LName,
					Email = u.Email,
					Roles = _userManager.GetRolesAsync(u).Result
				}).ToList() ;
				return View(users);
			}
			else
			{
				var user=await _userManager.FindByEmailAsync(email);

				var mappedUser = new UserViewModel()
				{
					Id = user.Id,
					FName = user.FName,
					LName = user.LName,
					Email = user.Email,
					Roles = _userManager.GetRolesAsync(user).Result
				};
				return View(new List<UserViewModel>() { mappedUser} );
			}

		}

        public async Task<IActionResult> Details(string  id, string ViewName = "Details")
        {
            if (id is null)
                return BadRequest();

            var user = await _userManager.FindByIdAsync(id);

            if (user is null)
                return NotFound();

            var mappedUser = _mapper.Map<ApplicationUser, UserViewModel>(user);


            return View(ViewName, mappedUser);
        }

        public async Task<IActionResult> Edit(string id)
        {

            return await Details(id, "Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] string id, UserViewModel updatedUser)
        {
            if (id != updatedUser.Id)
                return BadRequest();

            //if (ModelState.IsValid)
            //{
                try
                {
                  var user=await _userManager.FindByIdAsync(id);

                    user.FName = updatedUser.FName;
                    user.LName= updatedUser.LName;
                    user.PhoneNumber = updatedUser.PhoneNumber;
                   

                    //user.Email = updatedUser.Email;
                    //user.SecurityStamp = Guid.NewGuid().ToString();


                    await _userManager.UpdateAsync(user);

                    return RedirectToAction(nameof(Index));

                }
                catch (Exception ex)
                {

                    //1. Log Exception
                    //2. Friendly message
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            //}


            return View(updatedUser);
        }

        public async Task<IActionResult> Delete(string id)
        {

            return await Details(id, "Delete");
        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmDelete( string id)
        {

            try
            {
                var user = await _userManager.FindByIdAsync(id);

                await _userManager.DeleteAsync(user);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                //1. Log Exception
                //2. Friendly message

                ModelState.AddModelError(string.Empty, ex.Message);
                return RedirectToAction("Error","Home");
            }
        }

    }
}

Demo.PL/Views/Shared/_AuthLayout.cshtml
<!--
Author: Colorlib
Author URL: https://colorlib.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
	<title>Creative Colorlib @ViewData["Title"] Form</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- Custom Theme files -->
	<link href="~/css/authLayout.css" rel="stylesheet" type="text/css" media="all" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1>Creative @ViewData["Title"] Form</h1>
		@RenderBody()
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	@await RenderSectionAsync("ValidationScriptSection", required: false)
</body>
</html>

Demo.PL/Views/Shared/_ButtonsPartial.cshtml
@Model string

<td>
    <a asp-action="Details" asp-route-id="@Model" class="btn btn-warning">
        <i class="fas fa-eye"></i> Details
    </a>
</td>
<td>
    <a asp-action="Edit" asp-route-id="@Model" class="btn btn-success">
        <i class="fas fa-edit"></i> Update
    </a>
</td>
<td>
    <a asp-action="Delete" asp-route-id="@Model" class="btn btn-danger">
        <i class="fas fa-trash"></i> Delete
    </a>
</td>

Demo.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Demo.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Demo.PL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Demo.PL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item ml-auto">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item ml-auto">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                        </li> 
                        <li class="nav-item ml-auto">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="SignOut">SignOut</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Demo.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("ValidationScriptSection", required: false)
</body>
</html>