Demo.PL/Controllers/DepartmentController.cs
using Demo.BLL.Interfaces;
using Demo.DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Demo.PL.Controllers
{
    [Authorize]
    public class DepartmentController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        //private readonly IDepartmentRepository _departmentRepository;

        public DepartmentController(IUnitOfWork unitOfWork/*IDepartmentRepository departmentRepository*/)
        {
            _unitOfWork = unitOfWork;
            //_departmentRepository = departmentRepository;
        }

        public IActionResult Index()
        {
            var deparmetns=_unitOfWork.DepartmentRepository.GetAll();
            return View(deparmetns);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Department department)
        {
            if(ModelState.IsValid)
            {
                 _unitOfWork.DepartmentRepository.Add(department);
                var count =_unitOfWork.Complete();
                if (count > 0)                
                    TempData["Message"] = "Department is created successfully";
                
                else
                    TempData["Message"] = "An Error has occured, Department not created";

                return RedirectToAction(nameof(Index));
            }

            return View(department);
        }

        public IActionResult Details(int? id,string ViewName="Details")
        {
            if(!id.HasValue)
                return BadRequest();

            var department = _unitOfWork.DepartmentRepository.Get(id.Value);
            if(department is null)
                return NotFound();

            return View(ViewName, department);
        }

        public IActionResult Edit(int? id)
        {
            ///if (!id.HasValue)
            ///    return BadRequest();
            ///var department = _departmentRepository.Get(id.Value);
            ///if (department is null)
            ///    return NotFound();
            ///return View(department);

            return Details(id,"Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([FromRoute]int id,Department department)
        {
            if(id!=department.Id)
                return BadRequest();

            if(ModelState.IsValid)
            {
                try
                {

                    _unitOfWork.DepartmentRepository.Update(department);
                    _unitOfWork.Complete();
                    return RedirectToAction(nameof(Index));

                }
                catch (Exception ex)
                {

                    //1. Log Exception
                    //2. Friendly message
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }

          
            return View(department);
        }

        public IActionResult Delete(int? id)
        {
       
            return Details(id, "Delete");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete([FromRoute] int id,Department department)
        {
            if (id != department.Id)
                return BadRequest();

            try
            {
                _unitOfWork.DepartmentRepository.Delete(department);
                _unitOfWork.Complete();
                return RedirectToAction(nameof(Index)); 
            }
            catch (Exception ex)
            {
                //1. Log Exception
                //2. Friendly message

                ModelState.AddModelError(string.Empty, ex.Message);
                return View(department);
            }
        }
    }
}

Demo.PL/Views/Department/Create.cshtml
@model Department

@{
    ViewData["Title"] = "Create";
}

<h1>Create New Department</h1>

<br />

<form asp-action="Create">

    <partial name="PartialViews/CreateEditDepartmentPartial" />

    <div class="mt-3 ">
        <input class="btn btn-primary" type="submit" value="Create" />
        <a class="btn btn-light" asp-controller="Department" asp-action="Index">Back To List</a>
    </div>
</form>


@section ValidationScriptSection {
    <partial name="_ValidationScriptsPartial" />

    @*   <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script> *@
}

Demo.PL/Views/Department/Delete.cshtml
@model Department
@{
    ViewData["Title"] = "Delete";
}

<h1>Are you Sure to delete this department?</h1>

<form asp-action="Delete">
    <div asp-validation-summary="All"></div>

    <partial name="PartialViews/DetailsDeleteDepartmentPartial" />

    <div class="mt-3 ">
        <input class="btn btn-danger" type="submit" value="Delete" />
        <a class="btn btn-secondary" asp-controller="Department" asp-action="Index">Cancle</a>
    </div>
</form>

Demo.PL/Views/Department/Details.cshtml
@model Department
@{
    ViewData["Title"] = "Details";
}

<h1>Department Details</h1>

<br />
<br />

<div>

    <partial name="PartialViews/DetailsDeleteDepartmentPartial" />

    <div class="mt-3 ">
        <a class="btn btn-secondary" asp-controller="Department" asp-action="Index">Back To List</a>
    </div>
</div>

Demo.PL/Views/Department/Edit.cshtml
@model Department

@{
    ViewData["Title"] = "Create";
}

<h1>Update Department</h1>

<br />

<form asp-action="Edit">

    <partial name="PartialViews/CreateEditDepartmentPartial" />

    <div class="mt-3 ">
        <input class="btn btn-primary" type="submit" value="Update" />
        <a class="btn btn-light" asp-controller="Department" asp-action="Index">Back To List</a>
    </div>
</form>


@section ValidationScriptSection {
    <partial name="_ValidationScriptsPartial" />

    @*   <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script> *@
}

Demo.PL/Views/Department/Index.cshtml
@model IEnumerable<Department>

@{
    ViewData["Title"] = "Index";
}


@if (!string.IsNullOrEmpty(@TempData["Message"] as string))
{
    <div class="alert alert-primary">
        @TempData["Message"]
    </div>
}

<h1>All Departments</h1>

<br />
<br />

<a asp-controller="Department" asp-action="Create" class="btn btn-primary">Create New Department</a>

<br />

@if(Model.Count()>0)
{
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(D=>D.Code)</th>
                <th>@Html.DisplayNameFor(D=>D.Name)</th>
                <th>@Html.DisplayNameFor(D=>D.DateOfCreation)</th>
                <th>Details</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        </thead>

        <tbody>

           @foreach (var department in Model)
            {
                <tr>
                    <td>@department.Code</td>
                    <td>@department.Name</td>
                    <td>@department.DateOfCreation</td>
                    <partial name="_ButtonsPartial" model="@department.Id.ToString()" />
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="mt-4 alert alert-warning">
        <h3>There are no Departments</h3>
    </div>
    
}